### ISSUE TITLE
Merge equivalent CSS classes for IDL

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#1892]
Currently the IDL text contains several different CSS classes that does the same, for example:

```css
.idlInterfaceID,
.idlDictionaryID,
.idlCallbackID,
.idlEnumID {
  font-weight: bold;
  color: #005a9c;
}

/*.idlIterable*/

.idlIterableKeyType,
.idlIterableValueType {
  color: #005a9c;
}

/*.idlMaplike*/

.idlMaplikeKeyType,
.idlMaplikeValueType {
  color: #005a9c;
}

.idlAttrType,
.idlFieldType,
.idlMemberType {
  color: #005a9c;
}

.idlConstType {
  color: #005a9c;
}

.idlTypedefID,
.idlTypedefType {
  color: #005a9c;
}

.idlAttrName,
.idlFieldName,
.idlMemberName {
  color: #ff4500;
}

.idlAttrName a,
.idlFieldName a,
.idlMemberName a {
  color: #ff4500;
  border-bottom: 1px dotted #ff4500;
  text-decoration: none;
}
```

Recently I has been trying #1702 and found this complicates the code by forcing different class names for each IDL type names.

Maybe we can do something like:

```css
.idlID {
  font-weight: bold;
  color: #005a9c;
}

.idlContainer .idlID {
  font-weight: normal;
}
```

... so that we can use same CSS classes for IDL type names?
