### ISSUE TITLE
Missing .assertion css

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2005]
@Swapnilr1, looks like we got so excited about the JS side, we forgot to actually add the CSS part 😂 

I think we want: 

```CSS
.assertion {
  border-color: #AAA;
  background: #EEE;
  border-left: .5em solid;
  padding: 0.3em;
}
```

Added to:
https://github.com/w3c/respec/blob/develop/js/core/css/issues-notes.css

And we want to check here for ".assertion" being in the document:
https://github.com/w3c/respec/blob/develop/src/core/issues-notes.js#L293
