### ISSUE TITLE
table.simple style is not dark-mode friendly

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/respec#4667]
The respec style sheet includes
```css
.simple tr:nth-child(even) {
  background: #f0f6ff;
}
```

when using dark mode, the cell background remains light colored (which isn't great); more problematically, the text in the cell is also very light, making it unreadable.

The rule above should either have a set text color, or better, use variable-defined colors to work with dark mode.
